//文法のトップ、全ての入力文字列はここを起点に解析される
?start : cmd+

// 命令の種類
?cmd : out_cmd
     | var_cmd
     | if_stmt

// 命令のルール
// "out"のあとに文が続く
out_cmd : "out" expression

// "変数名=" のあとに文が続く
var_cmd : var_list "=" expr_list

var_list : var_name ("," var_name)*
expr_list : expression ("," expression)*

// 文のトップ
?expression : logical_or

// 論理和
?logical_or : logical_or "||" logical_and -> log_or
            | logical_and

// 論理積
?logical_and : logical_and "&&" comparison -> log_and
             | comparison

// 比較演算子
?comparison : comparison "==" add_expr -> eq
            | comparison "!=" add_expr -> neq
            | comparison "<=" add_expr -> lte
            | comparison ">=" add_expr -> gte
            | comparison "<"  add_expr -> lt
            | comparison ">"  add_expr -> gt
            | add_expr

// 四則演算
?add_expr   : add_expr "+" mul_expr -> add
            | add_expr "-" mul_expr -> sub
            | mul_expr  

?mul_expr   : mul_expr "*" pow_expr -> mul
            | mul_expr "/" pow_expr -> div
            | mul_expr "/_" pow_expr -> rounddiv
            | mul_expr "%" pow_expr -> mod
            | pow_expr  

?pow_expr   : primary "^^" pow_expr -> intpow
            | primary "**" pow_expr -> doublepow
            | primary

?primary    : STRING -> string
            | NUMBER -> number
            | "true" -> true_lit
            | "false" -> false_lit
            | "!" primary -> log_not
            | var_name
            | "read" -> read_expr
            | "iread" -> iread_expr
            | "modpow" "(" expression "," expression "," expression ")" -> modpow
            | "(" expression ")"

// 変数名
?var_name : CNAME -> cname

// ステートメントブロック
block: cmd+

// if文
if_stmt: "if" expression [":"] block ("elif" expression [":"] block)* ["else" [":"] block] "end"

// Larkの組み込み正規表現をインポート
%import common.ESCAPED_STRING -> STRING
%import common.SIGNED_NUMBER  -> NUMBER
%import common.CNAME
%import common.WS
%ignore WS // 空白文字を無視