//文法のトップ、全ての入力文字列はここを起点に解析される
?start : cmd+

// 命令の種類
?cmd : out_cmd
     | var_cmd

// 命令のルール
// "out"のあとに文が続く
out_cmd : "out" expression

// "変数名=" のあとに文が続く
var_cmd : var_name "=" expression

// 式 (expression)
?expression : STRING -> string // 文字列
            | NUMBER -> number // 数字
            | "read" -> read_expr // str型の入力
            | "iread" -> iread_expr // int型の入力
            | var_name // 変数名
            | expression "+" expression -> add

?var_name : CNAME -> cname

// Larkの組み込み正規表現をインポート
%import common.ESCAPED_STRING -> STRING
%import common.SIGNED_NUMBER  -> NUMBER
%import common.CNAME
%import common.WS
%ignore WS // 空白文字を無視